version: "3"
services:
  redis:
    image: redis:latest
    networks:
      - sail
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: QNA_database
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_bin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sail
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: QNA_database
      GOOGLE_CLIENT_ID: 408074599990-tsmj1qpfc5okviescmhk49m89qno1hmg.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      URL_WEB: http://localhost:3000
      URL_API: http://trongphan5301.click
      GMAIL_USER: questionandanswerit@gmail.com
      GMAIL_PASSWORD: cksy vmya goao qwne
      MAIL_HOST: smtp.gmail.com
    ports:
      - "3001:3001"
    networks:
      - sail
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - sail

volumes:
  mysql-data:

networks:
  sail:
