version: "3"
services:
  redis:
    image: redis:latest
    networks:
      - sail
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: QNA_database
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_bin
    ports:
      - "3306:3306"
    networks:
      - sail

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run start:dev
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: QNA_database
      GOOGLE_CLIENT_ID: 408074599990-tsmj1qpfc5okviescmhk49m89qno1hmg.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      URL_WEB: http://localhost:3000
      URL_API: http://localhost:3001
      GMAIL_USER: questionandanswerit@gmail.com
      GMAIL_PASSWORD: cksy vmya goao qwne
      MAIL_HOST: smtp.gmail.com
    ports:
      - "3001:3001"
    networks:
      - sail
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   working_dir: /usr/src/app
  #   command: yarn run dev
  #   depends_on:
  #     - backend
  #   environment:
  #     - WDS_SOCKET_HOST=127.0.0.1
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - sail
  #   restart: always

networks:
  sail:
