export const url = {
  AUTHORIZE: "/api/auth",
  SIGN_IN: "/api/auth/signin",
  SIGN_IN_NEW: "/api/auth/login-new",
  SIGN_UP: "/api/auth/signup",
  FORGOT_PASSWORD: "/api/user/ask-to-reset-password",
  RESET_PASSWORD: "/api/user/do-reset-password",
  CHECK_EXISTS_USER: "/api/user/check-exists-user",
  USER: "/api/user",
  QUESTION: "/api/question",
  VOTE_QUESTION: "/api/question/vote",
  QUESTION_LIST: "/api/question",
  REFRESH_TOKEN: "/api/auth/refresh",
  SIGN_OUT: "/api/auth/logout",
  ANSWER: "/api/answer",
  APPROVE_ANSWER: "/api/answer/approve",
  TAG: "/api/tag",
  USER_PROFILE: "/api/user/profile",
  VOTE_ANSWER: "/api/answer/vote",
  COMMENT: "/api/comment",
  ACTIVITY_HISTORY: "/api/activity/history",
};
