export enum ActionTypes {
  REQUESTING = "REQUESTING",
  FINISHED_REQUEST = "FINISHED_REQUEST",
  REQUEST_GET_QUESTION = "REQUEST_GET_QUESTION",
  SUCCESS_GET_QUESTION = "SUCCESS_GET_QUESTION",
  FAILURE_GET_QUESTION = "FAILURE_GET_QUESTION",
  REQUEST_GET_QUESTION_LIST = "REQUEST_GET_QUESTION_LIST",
  SUCCESS_GET_QUESTION_LIST = "SUCCESS_GET_QUESTION_LIST",
  FAILURE_GET_QUESTION_LIST = "FAILURE_GET_QUESTION_LIST",
  REQUEST_GET_USER = "REQUEST_GET_USER",
  SUCCESS_GET_USER = "SUCCESS_GET_USER",
  FAILURE_GET_USER = "FAILURE_GET_USER",
}
