export const message = {
  ACCESS_DENIED: "ACCESS_DENIED",
  NOT_FOUND: {
    COMMENT: "COMMENT_NOT_FOUND",
    ANSWER: "ANSWER_NOT_FOUND",
    QUESTION: "QUESTION_NOT_FOUND",
    USER: "USER_NOT_FOUND",
  },
  NOT_AUTHOR: {
    COMMENT: "USER_IS_NOT_AUTHOR_COMMENT",
    ANSWER: "USER_IS_NOT_AUTHOR_ANSWER",
    QUESTION: "USER_IS_NOT_AUTHOR_QUESTION",
  },
  EXITED_EMAIL: "EMAIL_ALREADY_EXISTS",
  NOT_EXITS_USER: "USER_NOT_FOUND",
  PASSWORD_IS_INCORRECT: "PASSWORD_IS_INCORRECT",
};
