export const message = {
  ACCESS_DENIED: "ACCESS_DENIED",
  NOT_FOUND: {
    COMMENT: "COMMENT_NOT_FOUND",
    ANSWER: "ANSWER_NOT_FOUND",
    QUESTION: "QUESTION_NOT_FOUND",
    USER: "USER_NOT_FOUND",
    TAG: "TAG_NOT_FOUND",
    NOTIFICATION: "NOTIFICATION_NOT_FOUND",
  },
  NOT_AUTHOR: {
    COMMENT: "USER_IS_NOT_AUTHOR_COMMENT",
    ANSWER: "USER_IS_NOT_AUTHOR_ANSWER",
    QUESTION: "USER_IS_NOT_AUTHOR_QUESTION",
  },
  EXISTED: {
    TAG: "TAG_ALREADY_EXISTS",
    EMAIL: "EMAIL_ALREADY_EXISTS",
  },
  INVALID: {
    QUESTION: "INVALID_QUESTION",
  },
  REPUTATION: {
    NOT_ENOUGH: "NOT_ENOUGH_REPUTATION",
  },
  NOT_EXITS_USER: "USER_NOT_FOUND",
  PASSWORD_IS_INCORRECT: "PASSWORD_IS_INCORRECT",
  USER_IS_BLOCK: "USER_IS_BLOCK",
  QUESTION: {
    VERIFIED: "QUESTION_IS_VERIFIED",
    BLOCKED: "QUESTION_IS_BLOCKED",
  },
  TAG: {
    VERIFIED: "TAG_IS_VERIFIED",
  },
};
