export const notificationText = {
  QUESTION: {
    CREATE: "CREATED_QUESTION",
    UPDATE: "UPDATED_QUESTION",
    DELETE: "DELETED_QUESTION",
    VERIFY: "VERIFIED_QUESTION",
    BLOCK: "BLOCKED_QUESTION",
  },
  ANSWER: {
    CREATE: "CREATED_ANSWER",
    UPDATE: "UPDATED_ANSWER",
    DELETE: "DELETED_ANSWER",
    ACCEPT: "ACCEPTED_ANSWER",
    UN_APPROVE: "UN_APPROVED_ANSWER",
  },
  COMMENT: {
    CREATE: "CREATED_COMMENT",
    UPDATE: "UPDATED_COMMENT",
    DELETE: "DELETED_COMMENT",
  },
  VOTE: {
    UP: "UP_VOTE",
    DOWN: "DOWN_VOTE",
    CANCEL_UP: "CANCEL_UP_VOTE",
    CANCEL_DOWN: "CANCEL_DOWN_VOTE",
    CHANGE_UP_TO_DOWN: "CHANGE_VOTE_UP_TO_DOWN",
    CHANGE_DOWN_TO_UP: "CHANGE_VOTE_DOWN_TO_UP",
  },
  TAG: {
    VERIFY: "VERIFIED_TAG",
  },
};
export const notificationTextDesc = {
  QUESTION: {
    CREATE: "DESCRIPTION_CREATED_QUESTION",
    UPDATE: "DESCRIPTION_UPDATED_QUESTION",
    DELETE: "DESCRIPTION_DELETED_QUESTION",
  },
  ANSWER: {
    CREATE: "DESCRIPTION_CREATED_ANSWER",
    UPDATE: "DESCRIPTION_UPDATED_ANSWER",
    DELETE: "DESCRIPTION_DELETED_ANSWER",
    ACCEPT: "DESCRIPTION_ACCEPTED_ANSWER",
    UN_APPROVE: "DESCRIPTION_UN_APPROVED_ANSWER",
  },
  COMMENT: {
    CREATE: "DESCRIPTION_CREATED_COMMENT",
    UPDATE: "DESCRIPTION_UPDATED_COMMENT",
    DELETE: "DESCRIPTION_DELETED_COMMENT",
  },
  VOTE: {
    UP: "DESCRIPTION_UP_VOTE",
    DOWN: "DESCRIPTION_DOWN_VOTE",
    CANCEL_UP: "DESCRIPTION_CANCEL_UP_VOTE",
    CANCEL_DOWN: "DESCRIPTION_CANCEL_DOWN_VOTE",
    CHANGE_UP_TO_DOWN: "DESCRIPTION_CHANGE_VOTE_UP_TO_DOWN",
    CHANGE_DOWN_TO_UP: "DESCRIPTION_CHANGE_VOTE_DOWN_TO_UP_VOTE",
  },
  TAG: {
    VERIFY: "DESCRIPTION_VERIFIED_TAG",
  },
};
